#!/usr/bin/env python3
"""Resolve a YouTube or YouTube Music reference to an official audio track."""

from __future__ import annotations

import argparse
import json
import re
import subprocess
import unicodedata
import urllib.parse
from typing import Any


WATCH_PREFIX = "https://www.youtube.com/watch?v="
MUSIC_SEARCH_PREFIX = "https://music.youtube.com/search?q="
WATCH_RE = re.compile(
    r"(?:https?://)?(?:www\.|m\.)?(?:music\.)?youtube\.com/watch\?[^#\s]*\bv=([A-Za-z0-9_-]{11})"
)
SHORT_RE = re.compile(r"(?:https?://)?youtu\.be/([A-Za-z0-9_-]{11})")
MUSIC_BROWSE_RE = re.compile(r"(?:https?://)?music\.youtube\.com/browse/([A-Za-z0-9_-]+)")


def arguments() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("reference", help="YouTube/Music URL, youtu.be URL, or search query")
    return parser.parse_args()


def _run_json(command: list[str]) -> dict[str, Any]:
    if command and command[0] == "yt-dlp":
        command = ["yt-dlp", "-4", *command[1:]]
    result = subprocess.run(command, check=True, capture_output=True, text=True)
    payload = json.loads(result.stdout)
    if not isinstance(payload, dict):
        raise RuntimeError("yt-dlp returned a non-object JSON payload")
    return payload


def canonical_watch_url(video_id: str) -> str:
    return f"{WATCH_PREFIX}{video_id}"


def extract_video_id(value: str) -> str | None:
    for pattern in (WATCH_RE, SHORT_RE):
        match = pattern.search(value)
        if match:
            return match.group(1)
    return None


def is_music_browse_url(value: str) -> bool:
    return MUSIC_BROWSE_RE.search(value) is not None


def looks_like_youtube_reference(value: str) -> bool:
    return extract_video_id(value) is not None or is_music_browse_url(value)


def canonicalize_reference(value: str) -> str:
    video_id = extract_video_id(value)
    if video_id:
        return canonical_watch_url(video_id)
    return value


def inspect_track(url: str) -> dict[str, Any]:
    return _run_json(["yt-dlp", "--no-playlist", "--dump-single-json", "--skip-download", url])


def inspect_flat(url: str) -> dict[str, Any]:
    return _run_json(["yt-dlp", "--flat-playlist", "--dump-single-json", url])


def normalize_text(value: str) -> str:
    decomposed = unicodedata.normalize("NFKD", value)
    stripped = "".join(char for char in decomposed if not unicodedata.combining(char))
    lowered = stripped.casefold()
    lowered = lowered.replace("&", " and ")
    lowered = re.sub(r"[^a-z0-9]+", " ", lowered)
    return re.sub(r"\s+", " ", lowered).strip()


def is_official_track(metadata: dict[str, Any]) -> bool:
    description = str(metadata.get("description") or "")
    channel = str(metadata.get("channel") or metadata.get("uploader") or "")
    return (
        "Provided to YouTube by" in description
        or "Auto-generated by YouTube" in description
        or channel.endswith(" - Topic")
    )


def target_title(metadata: dict[str, Any]) -> str:
    return str(metadata.get("track") or metadata.get("title") or "").strip()


def target_artist(metadata: dict[str, Any]) -> str:
    return str(metadata.get("artist") or metadata.get("uploader") or metadata.get("channel") or "").strip()


def source_title_hint(metadata: dict[str, Any]) -> str:
    title = str(metadata.get("track") or metadata.get("title") or "").strip()
    title = title.split("|")[0]
    title = re.sub(r"\s*\((?:lyrical|lyrics?|official(?: audio| video)?)\)\s*", " ", title, flags=re.I)
    return re.sub(r"\s+", " ", title).strip()


def source_artist_hint(metadata: dict[str, Any]) -> str:
    if metadata.get("artist"):
        return str(metadata["artist"]).strip()
    description = str(metadata.get("description") or "")
    match = re.search(r"(?im)^\s*singers?\s*:\s*(.+?)\s*$", description)
    if match:
        return match.group(1).strip()
    title_parts = [part.strip() for part in str(metadata.get("title") or "").split("|")]
    if len(title_parts) > 1 and 1 <= len(title_parts[1].split()) <= 5:
        return title_parts[1]
    channel = str(metadata.get("channel") or metadata.get("uploader") or "").strip()
    return channel.removesuffix(" - Topic") if channel.endswith(" - Topic") else ""


def title_similarity(left: str, right: str) -> int:
    if not left or not right:
        return 0
    if left == right:
        return 120
    if left in right or right in left:
        return 85
    left_tokens = set(left.split())
    right_tokens = set(right.split())
    if not left_tokens or not right_tokens:
        return 0
    overlap = len(left_tokens & right_tokens)
    union = len(left_tokens | right_tokens)
    return int((overlap / union) * 60)


def artist_similarity(left: str, right: str) -> int:
    if not left or not right:
        return 0
    if left == right:
        return 45
    left_tokens = set(left.split())
    right_tokens = set(right.split())
    overlap = len(left_tokens & right_tokens)
    if overlap == 0:
        return 0
    return min(35, overlap * 12)


def summarize_formats(metadata: dict[str, Any]) -> list[dict[str, Any]]:
    formats = []
    for item in metadata.get("formats") or []:
        if item.get("vcodec") != "none":
            continue
        formats.append({
            "format_id": item.get("format_id"),
            "ext": item.get("ext"),
            "acodec": item.get("acodec"),
            "abr": item.get("abr"),
            "asr": item.get("asr"),
            "filesize": item.get("filesize"),
            "format_note": item.get("format_note"),
            "protocol": item.get("protocol"),
        })
    formats.sort(
        key=lambda item: (
            float(item.get("abr") or 0),
            float(item.get("asr") or 0),
            float(item.get("filesize") or 0),
        ),
        reverse=True,
    )
    return formats[:5]


def candidate_from_metadata(
    metadata: dict[str, Any],
    *,
    source: str,
    search_query: str,
    expected_title: str,
    expected_artist: str,
) -> dict[str, Any]:
    actual_title = normalize_text(target_title(metadata))
    actual_artist = normalize_text(target_artist(metadata))
    score = 0
    reasons: list[str] = []
    if is_official_track(metadata):
        score += 45
        reasons.append("official-audio markers present")
    title_score = title_similarity(normalize_text(expected_title), actual_title)
    if title_score:
        score += title_score
        reasons.append(f"title match +{title_score}")
    artist_score = artist_similarity(normalize_text(expected_artist), actual_artist)
    if artist_score:
        score += artist_score
        reasons.append(f"artist match +{artist_score}")
    if search_query:
        query_score = title_similarity(normalize_text(search_query), normalize_text(f"{target_title(metadata)} {target_artist(metadata)}"))
        if query_score:
            score += min(25, query_score // 3)
            reasons.append("query overlap")
    return {
        "id": metadata.get("id"),
        "url": canonical_watch_url(str(metadata.get("id"))),
        "title": metadata.get("title"),
        "track": metadata.get("track"),
        "artist": metadata.get("artist"),
        "album": metadata.get("album"),
        "channel": metadata.get("channel") or metadata.get("uploader"),
        "duration_seconds": metadata.get("duration"),
        "official": is_official_track(metadata),
        "score": score,
        "score_reasons": reasons,
        "source": source,
        "description_excerpt": str(metadata.get("description") or "")[:180],
        "best_audio_formats": summarize_formats(metadata),
        "metadata": metadata,
    }


def expand_entry_candidates(
    entry: dict[str, Any],
    *,
    search_query: str,
    expected_title: str,
    expected_artist: str,
) -> list[dict[str, Any]]:
    url = str(entry.get("url") or "")
    if not url:
        return []
    if "/watch?v=" in url:
        try:
            metadata = inspect_track(url)
        except subprocess.CalledProcessError:
            return []
        return [candidate_from_metadata(
            metadata,
            source=url,
            search_query=search_query,
            expected_title=expected_title,
            expected_artist=expected_artist,
        )]
    if "/browse/" in url:
        playlist = inspect_flat(url)
        results: list[dict[str, Any]] = []
        for item in (playlist.get("entries") or [])[:12]:
            if not isinstance(item, dict) or "/watch?v=" not in str(item.get("url") or ""):
                continue
            try:
                metadata = inspect_track(str(item["url"]))
            except subprocess.CalledProcessError:
                continue
            results.append(candidate_from_metadata(
                metadata,
                source=f"{url} -> {item['url']}",
                search_query=search_query,
                expected_title=expected_title,
                expected_artist=expected_artist,
            ))
        return results
    return []


def choose_candidate(candidates: list[dict[str, Any]], *, reference: str) -> dict[str, Any]:
    if not candidates:
        raise RuntimeError(f"no candidate tracks found for {reference!r}")
    ordered = sorted(candidates, key=lambda item: (item["score"], item["official"], -(item.get("duration_seconds") or 0)), reverse=True)
    best = ordered[0]
    second = ordered[1] if len(ordered) > 1 else None
    if second and second["score"] >= best["score"] - 8 and second["id"] != best["id"]:
        raise RuntimeError(f"official audio search remained ambiguous for {reference!r}")
    if not best["official"] or (best["score"] < 70 and len(candidates) > 1):
        raise RuntimeError(f"official audio not confidently identified for {reference!r}")
    return best


def search_candidates(query: str, *, expected_title: str = "", expected_artist: str = "") -> tuple[list[dict[str, Any]], str]:
    search_url = MUSIC_SEARCH_PREFIX + urllib.parse.quote(query)
    flat = inspect_flat(search_url)
    candidates: list[dict[str, Any]] = []
    for entry in (flat.get("entries") or [])[:10]:
        if not isinstance(entry, dict):
            continue
        candidates.extend(expand_entry_candidates(
            entry,
            search_query=query,
            expected_title=expected_title,
            expected_artist=expected_artist,
        ))
        if len(candidates) >= 12:
            break
    return candidates, search_url


def resolve_reference(reference: str) -> dict[str, Any]:
    canonical_input = canonicalize_reference(reference)
    if looks_like_youtube_reference(reference) and not is_music_browse_url(reference):
        inspected = inspect_track(canonical_input)
        chosen = candidate_from_metadata(
            inspected,
            source=canonical_input,
            search_query="",
            expected_title=target_title(inspected),
            expected_artist=target_artist(inspected),
        )
        if chosen["official"]:
            return {
                "input": reference,
                "canonical_input": canonical_input,
                "resolved_url": chosen["url"],
                "resolved_id": chosen["id"],
                "title": target_title(inspected),
                "artist": target_artist(inspected),
                "album": inspected.get("album"),
                "duration_seconds": inspected.get("duration"),
                "evidence": {
                    "mode": "direct-official",
                    "reason": chosen["score_reasons"],
                },
                "best_audio_formats": chosen["best_audio_formats"],
                "candidates": [strip_candidate(chosen)],
            }
        expected_title = source_title_hint(inspected)
        expected_artist = source_artist_hint(inspected)
        query = " ".join(part for part in [expected_title, expected_artist] if part).strip() or reference
        candidates, search_url = search_candidates(
            query,
            expected_title=expected_title,
            expected_artist=expected_artist,
        )
        best = choose_candidate(candidates, reference=reference)
        return build_result(reference, canonical_input, search_url, best, candidates, query)

    if is_music_browse_url(reference):
        playlist = inspect_flat(reference)
        query = str(playlist.get("title") or reference)
        candidates = []
        for entry in (playlist.get("entries") or [])[:12]:
            if isinstance(entry, dict):
                candidates.extend(expand_entry_candidates(
                    entry,
                    search_query=query,
                    expected_title="",
                    expected_artist="",
                ))
        best = choose_candidate(candidates, reference=reference)
        return build_result(reference, reference, reference, best, candidates, query)

    candidates, search_url = search_candidates(reference)
    best = choose_candidate(candidates, reference=reference)
    return build_result(reference, reference, search_url, best, candidates, reference)


def strip_candidate(candidate: dict[str, Any]) -> dict[str, Any]:
    return {
        "id": candidate["id"],
        "url": candidate["url"],
        "title": candidate["title"],
        "artist": candidate["artist"],
        "album": candidate["album"],
        "channel": candidate["channel"],
        "duration_seconds": candidate["duration_seconds"],
        "official": candidate["official"],
        "score": candidate["score"],
        "score_reasons": candidate["score_reasons"],
        "source": candidate["source"],
    }


def build_result(
    reference: str,
    canonical_input: str,
    search_url: str,
    best: dict[str, Any],
    candidates: list[dict[str, Any]],
    query: str,
) -> dict[str, Any]:
    metadata = best["metadata"]
    return {
        "input": reference,
        "canonical_input": canonical_input,
        "search_query": query,
        "search_url": search_url,
        "resolved_url": best["url"],
        "resolved_id": best["id"],
        "title": target_title(metadata),
        "artist": target_artist(metadata),
        "album": metadata.get("album"),
        "duration_seconds": metadata.get("duration"),
        "evidence": {
            "mode": "searched-official-audio",
            "reason": best["score_reasons"],
            "description_excerpt": best["description_excerpt"],
        },
        "best_audio_formats": best["best_audio_formats"],
        "candidates": [strip_candidate(candidate) for candidate in sorted(candidates, key=lambda item: item["score"], reverse=True)[:6]],
    }


def main() -> int:
    options = arguments()
    print(json.dumps(resolve_reference(options.reference), ensure_ascii=False, indent=2))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
