#!/usr/bin/env python3
"""Unit tests for YouTube Music official-audio resolution."""

from __future__ import annotations

import unittest
import subprocess
from unittest import mock

import resolve_youtube_music_audio as resolver


class ResolveYoutubeMusicAudioTests(unittest.TestCase):
    def test_extracts_and_canonicalizes_watch_ids(self) -> None:
        self.assertEqual(
            resolver.extract_video_id("https://music.youtube.com/watch?v=Q-QXJI6X7ks&si=test"),
            "Q-QXJI6X7ks",
        )
        self.assertEqual(
            resolver.extract_video_id("https://youtu.be/Q-QXJI6X7ks?feature=shared"),
            "Q-QXJI6X7ks",
        )
        self.assertEqual(
            resolver.canonicalize_reference("https://music.youtube.com/watch?v=Q-QXJI6X7ks&si=test"),
            "https://www.youtube.com/watch?v=Q-QXJI6X7ks",
        )

    def test_direct_official_track_returns_itself(self) -> None:
        metadata = {
            "id": "Q-QXJI6X7ks",
            "title": "Rom Rom Mein Basne Wale Ram",
            "track": "Rom Rom Mein Basne Wale Ram",
            "artist": "Asha Bhosle",
            "album": "Neel Kamal",
            "channel": "Asha Bhosle - Topic",
            "duration": 264,
            "description": "Provided to YouTube by Sa Re Ga Ma\n\nAuto-generated by YouTube.",
            "formats": [{"format_id": "251", "ext": "webm", "acodec": "opus", "vcodec": "none", "abr": 128}],
        }
        with mock.patch.object(resolver, "inspect_track", return_value=metadata):
            result = resolver.resolve_reference("https://youtu.be/Q-QXJI6X7ks")
        self.assertEqual(result["resolved_id"], "Q-QXJI6X7ks")
        self.assertEqual(result["resolved_url"], "https://www.youtube.com/watch?v=Q-QXJI6X7ks")
        self.assertEqual(result["evidence"]["mode"], "direct-official")

    def test_unofficial_title_and_description_yield_track_hints(self) -> None:
        metadata = {
            "title": "Hey Rom Rom Me Basnewale Ram (Lyrical) | Asha Bhosle | Neel Kamal (1968)",
            "description": "Song: Hey Rom Rom Mein Basne Wale Ram\nSingers: Asha Bhosle",
        }
        self.assertEqual(resolver.source_title_hint(metadata), "Hey Rom Rom Me Basnewale Ram")
        self.assertEqual(resolver.source_artist_hint(metadata), "Asha Bhosle")

    def test_unofficial_url_resolves_to_official_track(self) -> None:
        unofficial = {
            "id": "K272q6KnaMk",
            "title": "Hey Rom Rom Me Basnewale Ram (Lyrical) | Asha Bhosle | Neel Kamal(1968)",
            "track": None,
            "artist": None,
            "album": None,
            "channel": "Karaoke Hindi Songs",
            "uploader": "Karaoke Hindi Songs",
            "duration": 287,
            "description": "Lyrical upload",
            "formats": [],
        }
        official = {
            "id": "Q-QXJI6X7ks",
            "title": "Rom Rom Mein Basne Wale Ram",
            "track": "Rom Rom Mein Basne Wale Ram",
            "artist": "Asha Bhosle",
            "album": "Neel Kamal",
            "channel": "Asha Bhosle - Topic",
            "duration": 264,
            "description": "Provided to YouTube by Sa Re Ga Ma\n\nAuto-generated by YouTube.",
            "formats": [{"format_id": "251", "ext": "webm", "acodec": "opus", "vcodec": "none", "abr": 128}],
        }
        search = {"entries": [{"url": "https://music.youtube.com/watch?v=Q-QXJI6X7ks"}]}

        def fake_inspect_track(url: str) -> dict:
            if url.endswith("K272q6KnaMk"):
                return unofficial
            if url.endswith("Q-QXJI6X7ks"):
                return official
            raise AssertionError(url)

        with mock.patch.object(resolver, "inspect_track", side_effect=fake_inspect_track), \
             mock.patch.object(resolver, "inspect_flat", return_value=search):
            result = resolver.resolve_reference("https://youtu.be/K272q6KnaMk")
        self.assertEqual(result["resolved_id"], "Q-QXJI6X7ks")
        self.assertEqual(result["evidence"]["mode"], "searched-official-audio")

    def test_album_browse_entry_is_expanded_to_exact_track(self) -> None:
        browse = {"entries": [{"url": "https://music.youtube.com/watch?v=PeEh5DAOQac"}]}
        official = {
            "id": "PeEh5DAOQac",
            "title": "Kete Lagaichu Tu Naat Re",
            "track": "Kete Lagaichu Tu Naat Re",
            "artist": "Shri Chandra Bhanu Satpathy",
            "album": "Sai Naivedya",
            "channel": "Shirdi Sai Global Foundation",
            "duration": 299,
            "description": "Provided to YouTube by CDBaby\n\nAuto-generated by YouTube.",
            "formats": [{"format_id": "251", "ext": "webm", "acodec": "opus", "vcodec": "none", "abr": 128}],
        }
        with mock.patch.object(resolver, "inspect_flat", return_value=browse), \
             mock.patch.object(resolver, "inspect_track", return_value=official):
            result = resolver.resolve_reference("https://music.youtube.com/browse/MPREb_jZPic2pOk42")
        self.assertEqual(result["resolved_id"], "PeEh5DAOQac")
        self.assertEqual(result["title"], "Kete Lagaichu Tu Naat Re")

    def test_unavailable_search_candidate_is_skipped(self) -> None:
        entry = {"url": "https://music.youtube.com/watch?v=AAAAAAAAAAA"}
        failure = subprocess.CalledProcessError(1, ["yt-dlp"])
        with mock.patch.object(resolver, "inspect_track", side_effect=failure):
            self.assertEqual(
                resolver.expand_entry_candidates(
                    entry, search_query="song", expected_title="song", expected_artist="artist"
                ),
                [],
            )

    def test_ambiguous_candidates_fail_closed(self) -> None:
        search = {"entries": [
            {"url": "https://music.youtube.com/watch?v=AAAAAAAAAAA"},
            {"url": "https://music.youtube.com/watch?v=BBBBBBBBBBB"},
        ]}
        first = {
            "id": "AAAAAAAAAAA",
            "title": "Same Song",
            "track": "Same Song",
            "artist": "Artist One",
            "album": "Album",
            "channel": "Artist One - Topic",
            "duration": 200,
            "description": "Provided to YouTube by Label\n\nAuto-generated by YouTube.",
            "formats": [],
        }
        second = {
            "id": "BBBBBBBBBBB",
            "title": "Same Song",
            "track": "Same Song",
            "artist": "Artist Two",
            "album": "Album",
            "channel": "Artist Two - Topic",
            "duration": 201,
            "description": "Provided to YouTube by Label\n\nAuto-generated by YouTube.",
            "formats": [],
        }

        def fake_inspect_track(url: str) -> dict:
            if url.endswith("AAAAAAAAAAA"):
                return first
            if url.endswith("BBBBBBBBBBB"):
                return second
            raise AssertionError(url)

        with mock.patch.object(resolver, "inspect_flat", return_value=search), \
             mock.patch.object(resolver, "inspect_track", side_effect=fake_inspect_track):
            with self.assertRaisesRegex(RuntimeError, "ambiguous"):
                resolver.resolve_reference("Same Song")


if __name__ == "__main__":
    unittest.main()
